import test from 'node:test';import assert from 'node:assert/strict';
import {createAnalytics,safeLocation,ANALYTICS_CONSENT_KEY} from '../src/analytics.mjs';
function fixture(variant='a',hostname='enneo-funnel.netlify.app'){
 let time=1000000;const local=new Map(),session=new Map(),scripts=[];
 const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)});
 const win={location:{hostname,origin:'https://'+hostname,pathname:'/',search:'?email=private@example.com&utm_source=meta&utm_campaign=launch_01'},localStorage:storage(local),sessionStorage:storage(session)};
 const doc={visibilityState:'visible',cookie:'',createElement:()=>({}),head:{appendChild:s=>scripts.push(s)}};
 const options={id:'G-TEST123',now:()=>time};const a=createAnalytics(win,doc,variant,options);
 return {a,win,doc,scripts,local,session,options,tick:n=>time+=n,events:()=>Array.from(win.dataLayer||[],x=>Array.from(x)).filter(x=>x[0]==='event')};
}
test('no analytics script, identifiers or events before consent; localhost remains silent',()=>{const f=fixture();f.a.activate();f.a.screen('industry');f.a.complete('industry');assert.equal(f.scripts.length,0);assert.equal(f.session.size,0);assert.equal(f.win.gtag,undefined);f.a.setConsent(false);assert.equal(f.scripts.length,0);const dev=fixture('a','localhost');dev.a.setConsent(true);assert.equal(dev.scripts.length,0);});
test('unique stage views/completions survive repeated visits, strict-effect activation and reload',()=>{const f=fixture();f.a.setConsent(true);f.a.activate();f.a.screen('industry');f.a.complete('industry');f.a.complete('industry');f.a.screen('need');f.a.back('industry');f.a.screen('industry');assert.equal(f.events().filter(e=>e[1]==='funnel_view_industry').length,1);assert.equal(f.events().filter(e=>e[1]==='funnel_complete_industry').length,1);assert.equal(f.events().filter(e=>e[1]==='funnel_step_revisit').length,1);const reload=createAnalytics(f.win,f.doc,'a',f.options);reload.activate();reload.screen('industry');assert.equal(f.events().filter(e=>e[1]==='funnel_view_industry').length,1);});
test('B counts the industry question visible on landing; late consent invents no earlier stages',()=>{const b=fixture('b');b.a.setConsent(true);assert(b.events().some(e=>e[1]==='funnel_view_industry'));const late=fixture();late.a.screen('contact');late.a.setConsent(true);assert(!late.events().some(e=>e[1]==='funnel_view_landing'));assert(late.events().some(e=>e[1]==='funnel_view_contact'&&e[2].funnel_entry==='partial'));});
test('PII, answers and arbitrary error messages are excluded from payloads and URLs',()=>{const f=fixture();f.a.setConsent(true);f.a.event('funnel_form_error',{field:'email',error:'validation',email:'private@example.com',name:'Alice',message:'secret detail'});f.a.event('invented',{secret:'no'});const json=JSON.stringify(f.events());for(const value of ['private@example.com','Alice','secret detail','invented'])assert(!json.includes(value));assert(json.includes('error_field'));assert(!safeLocation(f.win.location).includes('email='));});
test('withdrawal blocks subsequent events and clears journey memory',()=>{const f=fixture();f.a.setConsent(true);f.a.setConsent(false);const n=f.events().length;f.a.screen('need');f.a.event('funnel_booking_confirmed');assert.equal(f.events().length,n);assert.equal(f.win['ga-disable-G-TEST123'],true);assert.equal(f.session.size,0);});
test('step duration excludes hidden-tab time and idle periods start partial measurement',()=>{const f=fixture();f.a.setConsent(true);f.a.screen('industry');f.tick(2000);f.doc.visibilityState='hidden';f.a.visibility();f.tick(60000);f.doc.visibilityState='visible';f.a.visibility();f.tick(3000);f.a.complete('industry');assert.equal(f.events().find(e=>e[1]==='funnel_complete_industry')[2].step_time_ms,5000);f.tick(31*60000);f.a.screen('need');assert.equal(f.events().at(-1)[2].funnel_entry,'partial');});
test('analytics consent does not grant Google advertising purposes',()=>{const f=fixture();f.a.setConsent(true);const updates=Array.from(f.win.dataLayer,x=>Array.from(x)).filter(x=>x[0]==='consent');assert(updates.every(x=>x[2].ad_storage!=='granted'&&x[2].ad_user_data!=='granted'&&x[2].ad_personalization!=='granted'));});

test('custom domain uses its own sanitized location and excludes spoof hosts',()=>{for(const host of ['funnel.enneo.ai','funnel.enneo.ai.evil.test','preview--enneo-funnel.netlify.app']){const f=fixture('a',host);f.a.activate();assert.equal(f.scripts.length,0);f.a.setConsent(true);assert.equal(f.scripts.length,host==='funnel.enneo.ai'?1:0);if(host==='funnel.enneo.ai')assert(f.events().every(e=>e[2].page_location.startsWith('https://funnel.enneo.ai/')));}});
