import test from 'node:test';import assert from 'node:assert/strict';import {createLeadHandler,parseLead} from '../netlify/functions/lead.mjs';
const payload={submissionId:'01234567-89ab-cdef-0123-456789abcdef',variant:'a',contact:{name:'Test',email:'test@example.com',company:'Example'},answers:{industry:'energy',need:'routine',volume:'medium',stage:'project'}};
const request=(body=payload,origin='https://enneo-funnel.netlify.app')=>new Request('https://enneo-funnel.netlify.app/api/lead',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const env={MAKE_FUNNEL_ENABLED:'true',MAKE_FUNNEL_WEBHOOK_URL:'https://hook.eu1.make.com/example',MAKE_FUNNEL_WEBHOOK_KEY:'test-only'};
test('fails closed on absent configuration, invalid fields, private requests and foreign origins',async()=>{const h=createLeadHandler({env:{}});assert.equal((await h(request())).status,503);assert.equal((await h(request(payload,'https://evil.test'))).status,403);assert.equal(parseLead({...payload,website:'spam'}),null);assert.equal(parseLead({...payload,answers:{...payload.answers,stage:'private'}}),null);assert.equal(parseLead({...payload,contact:{...payload.contact,email:[]}}),null);});
test('Make queue acceptance and mismatched responses never become Leads',async()=>{for(const body of ['Accepted',JSON.stringify({status:'saved',submission_id:'wrong',attio_record_id:payload.submissionId})]){const h=createLeadHandler({env,fetcher:async()=>new Response(body)});assert.equal((await h(request())).status,502);}});
test('only matching confirmed Attio save returns stable event ID',async()=>{let forwarded;const h=createLeadHandler({env,fetcher:async(url,args)=>{forwarded=JSON.parse(args.body);return Response.json({status:'saved',submission_id:payload.submissionId,attio_record_id:payload.submissionId});}});const r=await h(request({...payload,secret:'never-forward',contact:{...payload.contact,phone:'never-forward'}}));assert.equal(r.status,200);assert.equal((await r.json()).eventId,`lead-${payload.submissionId}`);assert(!JSON.stringify(forwarded).includes('never-forward'));});
test('CAPI payload is absent without consent and excludes contact fields with consent',async()=>{
 for(const consent of [false,true]){let forwarded;const h=createLeadHandler({env,fetcher:async(u,args)=>{forwarded=JSON.parse(args.body);return Response.json({status:'saved',submission_id:payload.submissionId,attio_record_id:payload.submissionId});}});await h(request({...payload,marketingConsent:consent}),{ip:'192.0.2.10'});if(!consent)assert.equal(forwarded.meta_json,null);else{const meta=JSON.parse(forwarded.meta_json);assert.equal(meta.data[0].event_name,'Lead');assert.equal(meta.data[0].event_id,'lead-'+payload.submissionId);assert.equal(meta.data[0].user_data.client_ip_address,'192.0.2.10');assert(!forwarded.meta_json.includes('test@example.com'));assert(!forwarded.meta_json.includes('Example'));}}
});
test('CRM note serialization safely preserves quotes and line breaks; exact retries share fingerprint',async()=>{const sent=[];const h=createLeadHandler({env,fetcher:async(u,args)=>{sent.push(JSON.parse(args.body));return Response.json({status:'saved',submission_id:payload.submissionId,attio_record_id:payload.submissionId});}});const p={...payload,contact:{...payload.contact,name:'Test "Quote"\nName'}};await h(request(p));await h(request(p));assert.equal(sent[0].fingerprint,sent[1].fingerprint);assert(JSON.parse(sent[0].note_content_json).includes(p.contact.name));});

test('exact HTTPS production origins accepted and retained in CAPI source URL',async()=>{for(const origin of ['https://funnel.enneo.ai','https://enneo-funnel.netlify.app','http://funnel.enneo.ai','https://funnel.enneo.ai.evil.test','null']){let forwarded;const h=createLeadHandler({env,fetcher:async(u,args)=>{forwarded=JSON.parse(args.body);return Response.json({status:'saved',submission_id:payload.submissionId,attio_record_id:payload.submissionId});}});const r=await h(request({...payload,variant:'b',marketingConsent:true},origin));const allowed=['https://funnel.enneo.ai','https://enneo-funnel.netlify.app'].includes(origin);assert.equal(r.status,allowed?200:403);if(allowed)assert.equal(JSON.parse(forwarded.meta_json).data[0].event_source_url,origin+'/2');else assert.equal(forwarded,undefined);}});
