import test from 'node:test';
import assert from 'node:assert/strict';
import {createTracking,CONSENT_KEY} from '../src/tracking.mjs';
function fixture(host='enneo-funnel.netlify.app',saved){const values=new Map(saved?[[CONSENT_KEY,saved]]:[]), scripts=[];const win={location:{hostname:host},localStorage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)}};const doc={createElement:()=>({}),head:{appendChild:s=>scripts.push(s)}};return{win,doc,scripts,tracking:createTracking(win,doc,'b')};}
test('no Meta script or events without consent, including rejected consent',()=>{const f=fixture();f.tracking.activate();f.tracking.event('funnel_start');assert.equal(f.win.fbq,undefined);f.tracking.setConsent(false);assert.equal(f.scripts.length,0);});
test('grant loads once and duplicate activation does not double-count page views',()=>{const f=fixture();f.tracking.setConsent(true);f.tracking.activate();f.tracking.event('funnel_start');assert.equal(f.scripts.length,1);assert.equal(f.win.fbq.queue.filter(x=>x[2]==='PageView').length,1);assert.equal(f.win.fbq.queue.filter(x=>x[2]==='FunnelStart').length,1);});
test('only allowed event metadata leaves the app; previews cannot become conversions',()=>{const f=fixture();f.tracking.setConsent(true);f.tracking.event('step_complete',{step:'industry',email:'secret@example.com',name:'private',answer:'energy'});for(const name of ['Lead','Schedule','qualification_result'])f.tracking.event(name);const q=JSON.stringify(f.win.fbq.queue);assert(!q.includes('secret'));assert(!q.includes('energy'));assert(!q.includes('Schedule'));assert(!q.includes('Lead'));assert(q.includes('industry'));});
test('revoke stops events; regrant does not duplicate PageView',()=>{const f=fixture();f.tracking.setConsent(true);f.tracking.setConsent(false);const n=f.win.fbq.queue.length;f.tracking.event('funnel_start');assert.equal(f.win.fbq.queue.length,n);assert.equal(f.win.fbq.queue.at(-1)[1],'revoke');f.tracking.setConsent(true);assert.equal(f.win.fbq.queue.filter(x=>x[2]==='PageView').length,1);});
test('local previews never send events and expired consent is ignored',()=>{const f=fixture('localhost');f.tracking.setConsent(true);assert.equal(f.scripts.length,0);assert.equal(fixture(undefined,JSON.stringify({allowed:true,at:1})).tracking.getConsent(),null);const restored=fixture(undefined,JSON.stringify({allowed:true,at:Date.now()}));restored.tracking.activate();assert.equal(restored.scripts.length,1);});
