import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Check, Clock3, ShieldCheck, LockKeyhole, Building2, MessagesSquare, Workflow, CircleHelp, X, CircleCheck, CalendarDays, Pencil, SlidersHorizontal, RotateCcw } from 'lucide-react';
import { questions, getVariant, labelFor, routeLead, validateContact, demoDays } from './flow.mjs';
import { Primary, Choices, Landing, StepProgress, MoreInfo } from './components.jsx';
const descriptions={a:'Vom Anliegen zum Ergebnis',b:'Direkt zum passenden Service',c:'Automatisierung mit Kontrolle'};
const CALENDLY='https://calendly.com/enneo-ai/demo';
function ReviewPanel({variant,onClose,events,answers}){return <div className="drawer-backdrop" onClick={onClose}><aside className="review-drawer" aria-modal="true" role="dialog" aria-labelledby="review-title" onClick={e=>e.stopPropagation()}><button className="icon-button close-drawer" onClick={onClose} aria-label="Testplan schließen"><X/></button><p className="eyebrow">FÜR ALEKSA & LARA</p><h2 id="review-title" tabIndex={-1}>Drei Einstiege.<br/>Ein fairer Vergleich.</h2><p className="drawer-intro">UI-Vorschau · Kein laufendes Experiment</p><div className="split-diagram">{['A','B','C'].map(v=><div key={v} className={variant===v.toLowerCase()?'current':''}><strong>{v}</strong><span>⅓ der Besucher</span></div>)}</div><h3>So ist der spätere Test geplant</h3><ul><li>Jede Anzeige liefert Besucher an alle drei Varianten.</li><li>Zufällige, beständige Zuordnung pro Besucher, sobald die produktive Messung eingerichtet ist.</li><li>Identische Fragen, Kontaktfelder und Buchungsstrecke.</li><li>Primär: qualifizierte wahrgenommene Demos je zugeordnetem Besucher.</li><li>Stichprobe und Laufzeit vor Testbeginn festlegen; Mehrfachvergleiche berücksichtigen.</li></ul><div className="review-note"><ShieldCheck size={20}/><p>In dieser Vorschau bleiben Angaben nur im Arbeitsspeicher. Keine Tracker, keine Übermittlung, keine echten Buchungen.</p></div><h3>Vorgesehener Lead-Pfad</h3><p>{routeLead(answers)==='incomplete'?'Noch nicht vollständig beantwortet.':routeLead(answers)==='not-business'?'Privatanliegen → Informationen statt Demo.':routeLead(answers)==='review'?'Bedarf weiter einordnen. Kein automatischer Ausschluss.':'Geschäftliches Anliegen → Demo vorbereiten. Sales-Freigabe offen.'}</p><h3>Lokaler Ablauf ({events.length})</h3><p className="small">Nur Ereignisse dieser Vorschau, ohne Kontaktangaben. Nach Neuladen gelöscht.</p><div className="event-list">{events.slice(-12).reverse().map((e,i)=><div key={i}><code>{e.name}</code><span>{e.step||e.variant?.toUpperCase()||'—'}</span></div>)}</div></aside></div>;}
export function App(){
 const params=new URLSearchParams(window.location.search),preview=params.get('preview')!=='0';
 const [variant,setVariant]=useState(()=>getVariant(params.get('variant'))),[step,setStep]=useState(-1);
 const [answers,setAnswers]=useState({industry:'',need:'',volume:'',stage:''});
 const [contact,setContact]=useState({name:'',email:'',company:''}),[errors,setErrors]=useState({});
 const [events,setEvents]=useState([{name:'funnel_view',variant}]),[drawer,setDrawer]=useState(false);
 const [day,setDay]=useState(''),[time,setTime]=useState(''),[faq,setFaq]=useState(null);
 const contentRef=useRef(null);
 const emit=(name,detail={})=>setEvents(old=>[...old,{name,variant,...detail}]);
 const move=next=>{setStep(next);window.scrollTo({top:0,behavior:'instant'});};
 useEffect(()=>{if(step!==-1)contentRef.current?.focus({preventScroll:true});},[step]);
 useEffect(()=>{if(!drawer)return;const previous=document.activeElement,oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';document.getElementById('review-title')?.focus();const handler=e=>{if(e.key==='Escape'){setDrawer(false);return;}if(e.key==='Tab'){const items=document.querySelector('.review-drawer').querySelectorAll('button,a[href],input,[tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement.id==='review-title')){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement.id==='review-title')){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',handler);previous?.focus();};},[drawer]);
 function start(){emit('funnel_start');const next=variant==='b'&&answers.industry?1:0;if(next===1)emit('step_complete',{step:'industry'});emit('step_view',{step:questions[next].key});move(next);}
 function next(){emit('step_complete',{step:questions[step].key});if(step===3){emit('qualification_result',{step:routeLead(answers)});move(answers.stage==='private'?7:4);}else{emit('step_view',{step:questions[step+1].key});move(step+1);}}
 function switchVariant(v){setVariant(v);setStep(-1);setAnswers({industry:'',need:'',volume:'',stage:''});setContact({name:'',company:'',email:''});setErrors({});setDay('');setTime('');setEvents([{name:'funnel_view',variant:v}]);const url=new URL(window.location.href);url.searchParams.set('variant',v);window.history.replaceState(null,'',url);window.scrollTo({top:0,behavior:'instant'});}
 function submitContact(e){e.preventDefault();const errs=validateContact(contact);setErrors(errs);if(Object.keys(errs).length){document.getElementById(Object.keys(errs)[0])?.focus();return;}emit('contact_preview_complete');emit('calendar_preview_view');move(5);}
 const queryStep=step>=0&&step<4;
 return <div className={`app variant-${variant} ${step>=0?'in-flow':''}`}><a href="#main-content" className="skip-link">Zum Inhalt</a>
 {preview&&<div className="preview-bar"><span className="preview-label">Design-Vorschau</span><div className="variant-switch" role="group" aria-label="Designvariante">{['a','b','c'].map(v=><button key={v} aria-pressed={variant===v} aria-label={`Variante ${v.toUpperCase()}: ${descriptions[v]}`} onClick={()=>switchVariant(v)}>{v.toUpperCase()}</button>)}</div><button className="test-plan" onClick={()=>setDrawer(true)}><SlidersHorizontal size={15}/><span>Testplan</span></button></div>}
 <header className="site-header"><button className="brand-button" onClick={()=>move(-1)} aria-label="Zurück zum Einstieg"><img src="/assets/logo.svg" width="142" height="29" alt="enneo"/></button><span className="header-divider"/><span className="header-title">{step<0?'Ihre Demo':'Ihre persönliche Demo'}</span>{step>=0&&<span className="header-duration"><Clock3 size={15}/>30 Min.</span>}</header>
 <div id="main-content" ref={contentRef} tabIndex={-1} className="main-content">
 {step===-1&&<Landing variant={variant} industry={answers.industry} onIndustry={value=>setAnswers({...answers,industry:value})} onStart={start}/>}
 {queryStep&&<main className="flow-layout" key={`step-${step}`}><aside className="flow-aside"><p className="eyebrow">PASSEND ZU IHREM ALLTAG</p><h2>Ihre Prozesse.<br/><em>Ihre Demo.</em></h2><p>Ein paar Angaben helfen uns, Ihnen die richtigen Möglichkeiten zu zeigen.</p><img src="/assets/agent-b.webp" width="1156" height="1360" alt=""/><div className="aside-time"><Clock3 size={19}/><span>30 Minuten.<br/>Raum für Ihre Fragen.</span></div></aside><section className="question-panel"><StepProgress step={step}/><h1>{questions[step].title}</h1><p className="question-intro">{questions[step].intro}</p><Choices question={questions[step]} value={answers[questions[step].key]} onSelect={value=>setAnswers(prev=>({...prev,[questions[step].key]:value}))}/><div className="question-actions"><button className="back-button" onClick={()=>move(step===0?-1:step-1)}><ArrowLeft size={18}/>Zurück</button><Primary onClick={next} disabled={!answers[questions[step].key]}>{step===3?'Demo zusammenstellen':'Weiter'}</Primary></div><p className="privacy-small"><LockKeyhole size={14}/>Ihre Angaben helfen uns bei der Gesprächsvorbereitung.</p></section></main>}
 {step===4&&<main className="flow-layout contact-layout"><aside className="summary"><p className="eyebrow">DARUM GEHT ES IN IHRER DEMO</p><h2>Ihr Service.<br/><em>Im Mittelpunkt.</em></h2><div className="summary-rows">{questions.map((q,i)=><div key={q.key}><span>{['Branche','Ihr Schwerpunkt','Anfragen pro Monat','Ihr Vorhaben'][i]}</span><strong>{labelFor(q.key,answers[q.key])}</strong><button onClick={()=>move(i)} aria-label={`${['Branche','Schwerpunkt','Anfragevolumen','Vorhaben'][i]} ändern`}><Pencil size={15}/></button></div>)}</div><div className="summary-expect"><CircleCheck size={20}/><p>Wir zeigen Ihnen einen passenden Beispielprozess und besprechen Integration, Freigaben und nächste Schritte.</p></div>{routeLead(answers)==='review'&&<p className="review-hint">Ihr Bedarf ist noch offen? Genau dafür nehmen wir uns im Gespräch Zeit.</p>}</aside><section className="contact-panel"><p className="eyebrow">FAST GESCHAFFT</p><h1>Für wen dürfen wir die Demo vorbereiten?</h1><p className="question-intro">Danach wählen Sie den passenden Termin.</p><form onSubmit={submitContact} noValidate>{[['name','Ihr Name','Vor- und Nachname','name'],['company','Unternehmen','Ihr Unternehmen','organization'],['email','Geschäftliche E-Mail-Adresse','name@unternehmen.de','email']].map(([key,label,placeholder,autoComplete])=><div key={key}><label htmlFor={key}>{label}</label><input id={key} name={key} spellCheck={key!=='email'} type={key==='email'?'email':'text'} autoComplete={autoComplete} required maxLength={key==='email'?254:160} value={contact[key]} onChange={e=>setContact({...contact,[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined} placeholder={placeholder}/>{errors[key]&&<p className="field-error" id={`${key}-error`} role="alert">{errors[key]}</p>}</div>)}<p className="form-privacy">Informationen zum Umgang mit Ihren Daten finden Sie in unserer <a href="https://www.enneo.ai/legal/privacy-policy" target="_blank" rel="noreferrer">Datenschutzerklärung</a>.</p><div className="prototype-note"><CircleHelp size={17}/><span>UI-Vorschau: Bitte nur Beispieldaten eingeben. Es werden keine Angaben versendet.</span></div><Primary type="submit">Zur Terminvorschau</Primary><button className="back-button form-back" type="button" onClick={()=>move(3)}><ArrowLeft size={17}/>Zurück</button></form></section></main>}
 {step===5&&<main className="booking-layout"><div className="booking-intro"><p className="eyebrow">IHRE DEMO MIT ENNEO</p><h1>Ein Termin.<br/><em>Konkrete Möglichkeiten.</em></h1><p>Wir nehmen uns Zeit für Ihre Serviceprozesse und Ihre Fragen.</p><div className="meeting-facts"><span><Clock3 size={18}/>30 Minuten</span><span><Workflow size={18}/>{labelFor('need',answers.need)}</span><span><Building2 size={18}/>{contact.company}</span></div><button className="back-button" onClick={()=>move(4)}><ArrowLeft size={18}/>Angaben bearbeiten</button></div><section className="booking-card"><div className="preview-badge">Terminvorschau · keine Live-Verfügbarkeit</div><h2>Wählen Sie einen Beispieltermin</h2><p className="calendar-month">Oktober 2026</p><div className="days" role="group" aria-label="Beispieltag wählen">{demoDays.map(d=><button key={d.id} aria-label={d.label} aria-pressed={day===d.id} onClick={()=>{setDay(d.id);setTime('');}}><span>{d.day}</span><strong>{d.date}</strong><span>Okt.</span></button>)}</div>{day&&<div className="time-section"><p>Beispielzeiten · Europe/Berlin</p><div className="times" role="group" aria-label="Beispielzeit wählen">{['09:30','11:00','14:30'].map(t=><button key={t} aria-pressed={time===t} onClick={()=>setTime(t)}>{t}</button>)}</div></div>}<Primary disabled={!day||!time} onClick={()=>{emit('booking_preview_complete');move(6);}}>Vorschau bestätigen</Primary><p className="booking-disclaimer">Diese Auswahl reserviert keinen Termin.</p><a className="live-calendar-link" href={CALENDLY} target="_blank" rel="noreferrer">Echten Enneo-Kalender öffnen<ArrowUpRight size={16}/></a></section></main>}
 {step===6&&<main className="success-panel"><div className="success-icon"><Check size={32}/></div><p className="eyebrow">VORSCHAU ABGESCHLOSSEN</p><h1>So endet die<br/><em>Demo-Buchung.</em></h1><p>Im fertigen Funnel erhalten Sie hier Ihre bestätigten Termindetails. In dieser Vorschau wurde kein Termin gebucht und keine E-Mail versendet.</p><div className="selected-appointment"><CalendarDays size={26}/><div><strong>{demoDays.find(d=>d.id===day)?.label}</strong><span>{time} Uhr · 30 Minuten · Europe/Berlin</span><small>Ausgewählter Beispieltermin</small></div></div><a className="primary" href={CALENDLY} target="_blank" rel="noreferrer">Echten Demo-Termin wählen<ArrowUpRight size={21}/></a><button className="back-button" onClick={()=>switchVariant(variant)}><RotateCcw size={17}/>Vorschau neu starten</button></main>}
 {step===7&&<main className="success-panel private-panel"><div className="success-icon"><MessagesSquare size={30}/></div><p className="eyebrow">SIE SUCHEN PERSÖNLICHEN KUNDENSERVICE</p><h1>Am besten direkt<br/><em>zu Ihrem Anbieter.</em></h1><p>enneo ist eine Software für Serviceteams. Bei Fragen zu Ihrer eigenen Rechnung oder Ihrem Vertrag hilft Ihnen das Unternehmen, bei dem Sie Kunde sind.</p><p>Bitte nutzen Sie dafür die Kontaktangaben auf Ihrer Rechnung oder der Website Ihres Anbieters.</p><button className="primary" onClick={()=>move(3)}>Ich suche eine Lösung für mein Unternehmen<ArrowLeft size={20}/></button></main>}
 </div>{step===-1&&<MoreInfo faq={faq} setFaq={setFaq}/>}<footer className="site-footer"><span>© 2026 enneo GmbH</span><nav aria-label="Rechtliche Informationen"><a href="https://www.enneo.ai/legal/imprint" target="_blank" rel="noreferrer">Impressum</a><a href="https://www.enneo.ai/legal/privacy-policy" target="_blank" rel="noreferrer">Datenschutz</a></nav></footer>{drawer&&<ReviewPanel variant={variant} onClose={()=>setDrawer(false)} answers={answers} events={events}/>}</div>;
}
