import { useState, useEffect } from 'react';
import './consent.css';
export function TrackingConsent({tracking,analytics}){
 const debug=new URLSearchParams(window.location.search).get('analytics_debug')==='1';
 const [diagnostic,setDiagnostic]=useState(null);
 useEffect(()=>{if(!debug)return;const timer=setInterval(()=>setDiagnostic(analytics.diagnostic()),1000);return()=>clearInterval(timer);},[analytics,debug]);
 const [open,setOpen]=useState(()=>tracking.getConsent()===null||analytics.getConsent()===null);
 const [statistics,setStatistics]=useState(()=>analytics.getConsent()===true),[marketing,setMarketing]=useState(()=>tracking.getConsent()===true);
 function choose(a,m){analytics.setConsent(a);tracking.setConsent(m);setStatistics(a);setMarketing(m);setOpen(false);}
 function show(){setStatistics(analytics.getConsent()===true);setMarketing(tracking.getConsent()===true);setOpen(true);}
 return <>{debug&&<details className="analytics-diagnostic"><summary>Statistik-Testdiagnose</summary><pre>{JSON.stringify(diagnostic,null,2)}</pre></details>}<button className="consent-settings" onClick={show}>Cookie-Einstellungen</button>{open&&<section className="consent-panel" aria-label="Cookie-Einstellungen"><h2>Ihre Cookie-Auswahl</h2><p>Sie entscheiden, ob wir die Nutzung dieses Funnels auswerten und Werbung messen dürfen. Der Funnel funktioniert auch ohne diese Einwilligungen.</p><label className="consent-option"><input type="checkbox" checked={statistics} onChange={e=>setStatistics(e.target.checked)}/><span><strong>Statistik · Google Analytics</strong><small>Schritte, Abbrüche, Gerät und Kampagnen auswerten. Google erhält Nutzungs- und technische Verbindungsdaten.</small></span></label><label className="consent-option"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span><strong>Marketing · Meta</strong><small>Werbung und Conversions messen. Meta erhält Ereignisse, Browserdaten und die besuchte URL.</small></span></label><p>Namen, E-Mails und Formularantworten senden wir nicht an diese Analysedienste. Sie können Ihre Auswahl jederzeit ändern.</p><a href="https://www.enneo.ai/legal/privacy-policy" target="_blank" rel="noreferrer">Datenschutz</a><div className="consent-actions"><button onClick={()=>choose(false,false)}>Nur notwendige</button><button onClick={()=>choose(true,true)}>Alle erlauben</button></div><button className="consent-save" onClick={()=>choose(statistics,marketing)}>Auswahl speichern</button></section>}</>;
}
